[package]
name = "online-python-src"
version = "0.1.0"
authors = ["sebasv <mail@sebastiaanvermeulen.nl>"]
edition = "2018"

[dependencies]
ndarray = {version = "0.12", features=["blas"]}
ndarray-linalg = {version = "0.10", default-features=false, features = ["openblas"]}